"""Registry and public dispatch helpers for concept SVG graphics."""

from __future__ import annotations

from pathlib import Path
from typing import Callable

from srkg.svg_graphics.concepts import (
    create_10_1_wave_equation,
    create_10_2_electromagnetic_waves,
    create_10_3_radiation_reaction,
    create_11_1_lorentz_invariance,
    create_11_2_gauge_fixing,
    create_1_1_inertial_frames,
    create_1_2_constancy_of_speed_of_light,
    create_1_3_principle_of_relativity,
    create_2_2_spacetime_event,
    create_2_3_principle_of_locality,
    create_3_1_metric_tensor,
    create_3_2_spacetime_interval,
    create_3_3_lorentz_transformations,
    create_3_4_light_cone,
    create_3_5_minkowski_diagram,
    create_4_1_proper_time,
    create_4_2_four_vectors,
    create_4_3_position_four_vector,
    create_4_4_velocity_four_vector,
    create_4_5_momentum_four_vector,
    create_4_6_mass_energy_equivalence,
    create_5_1_lagrangian,
    create_5_2_action_principle,
    create_5_3_euler_lagrange,
    create_5_4_canonical_momentum,
    create_5_5_hamiltonian_formalism,
    create_5_6_noethers_theorem,
    create_6_1_scalar_field,
    create_6_2_vector_field,
    create_6_3_field_lagrangian,
    create_6_4_field_equations,
    create_7_1_vector_potential,
    create_7_2_field_tensor,
    create_7_3_electric_field,
    create_7_4_magnetic_field,
    create_7_5_electromagnetic_field,
    create_7_6_four_current,
    create_7_7_maxwells_equations,
    create_8_1_gauge_invariance,
    create_8_3_minimal_coupling,
    create_8_4_lorentz_force_law,
    create_8_5_charge_conservation,
    create_8_6_lorenz_gauge,
    create_9_1_energy_momentum_tensor,
    create_9_2_poynting_vector,
    create_9_3_em_stress_energy,
    create_9_4_em_energy_density,
    create_gr_1_1_gravity_as_geometry,
    create_gr_1_2_equivalence_principle,
    create_gr_1_3_local_inertial_frame,
    create_gr_1_4_freely_falling_observer,
    create_gr_1_5_tidal_gravity,
    create_gr_7_1_stress_energy_tensor,
    create_gr_7_2_perfect_fluid,
    create_gr_7_3_energy_conditions,
    create_gr_7_4_covariant_conservation,
    create_gr_7_5_equation_of_state,
    create_gr_8_1_einstein_field_equations,
    create_gr_8_2_cosmological_constant,
    create_gr_8_3_einstein_hilbert_action,
    create_gr_8_4_stress_energy_variation,
    create_gr_8_5_trace_reversed_equations,
    create_gr_8_6_vacuum_field_equations,
    create_gr_9_1_weak_field_metric,
    create_gr_9_2_newtonian_limit,
    create_gr_9_3_gravitational_redshift,
    create_gr_9_4_light_deflection,
    create_gr_9_5_perihelion_precession,
    create_gr_9_6_post_newtonian_approximation,
    create_gr_10_1_schwarzschild_metric,
    create_gr_10_2_schwarzschild_radius,
    create_gr_10_3_event_horizon,
    create_gr_10_4_coordinate_singularity,
    create_gr_10_5_black_hole_singularity,
    create_gr_10_6_effective_potential_orbits,
    create_m_1_1_manifold,
    create_m_1_2_coordinate_chart,
    create_m_1_3_coordinate_transformation,
    create_m_1_4_worldline,
    create_m_1_5_tangent_space,
    create_m_1_6_cotangent_space,
    create_m_2_1_tensor_field,
    create_m_2_2_index_notation,
    create_m_2_3_tensor_transformation_law,
    create_gr_2_1_spacetime_metric,
    create_gr_2_2_inverse_metric,
    create_gr_2_3_volume_element,
    create_gr_3_1_line_element, create_gr_3_2_proper_time,
    create_gr_3_3_null_curve, create_gr_3_4_causal_structure,
    create_gr_3_5_local_flatness, create_gr_3_6_metric_signature,
    create_gr_4_1_connection, create_gr_4_2_christoffel_symbols,
    create_gr_4_3_covariant_derivative, create_gr_4_4_metric_compatibility,
    create_gr_4_5_torsion_free, create_gr_4_6_parallel_transport,
    create_gr_5_1_geodesic, create_gr_5_2_geodesic_equation,
    create_gr_5_3_geodesic_action, create_gr_5_4_four_velocity,
    create_gr_5_5_four_acceleration, create_gr_5_6_geodesic_deviation,
    create_gr_6_1_riemann_tensor, create_gr_6_2_ricci_tensor,
    create_gr_6_3_ricci_scalar, create_gr_6_4_einstein_tensor,
    create_gr_6_5_bianchi_identity, create_gr_6_6_curvature_invariants,
)

IMPLEMENTED_NODE_IDS = (
    '1.1',
    '1.2',
    '1.3',
    '2.2',
    '2.3',
    '3.1',
    '3.2',
    '3.3',
    '3.4',
    '3.5',
    '4.1',
    '4.2',
    '4.3',
    '4.4',
    '4.5',
    '4.6',
    '5.1',
    '5.2',
    '5.3',
    '5.4',
    '5.5',
    '5.6',
    '6.1',
    '6.2',
    '6.3',
    '6.4',
    '7.1',
    '7.2',
    '7.3',
    '7.4',
    '7.5',
    '7.6',
    '7.7',
    '8.1',
    '8.3',
    '8.4',
    '8.5',
    '8.6',
    '9.1',
    '9.2',
    '9.3',
    '9.4',
    '10.1',
    '10.2',
    '10.3',
    '11.1',
    '11.2',
    'M 1.1',
    'M 1.2',
    'M 1.3',
    'M 1.4',
    'M 1.5',
    'M 1.6',
    'M 2.1',
    'M 2.2',
    'M 2.3',
    'GR 1.1',
    'GR 1.2',
    'GR 1.3',
    'GR 1.4',
    'GR 1.5',
    'GR 2.1',
    'GR 2.2',
    'GR 2.3',
    'GR 3.1', 'GR 3.2', 'GR 3.3', 'GR 3.4', 'GR 3.5', 'GR 3.6',
    'GR 4.1', 'GR 4.2', 'GR 4.3', 'GR 4.4', 'GR 4.5', 'GR 4.6',
    'GR 5.1', 'GR 5.2', 'GR 5.3', 'GR 5.4', 'GR 5.5', 'GR 5.6',
    'GR 6.1', 'GR 6.2', 'GR 6.3', 'GR 6.4', 'GR 6.5', 'GR 6.6',
    'GR 7.1',
    'GR 7.2',
    'GR 7.3',
    'GR 7.4',
    'GR 7.5',
    'GR 8.1',
    'GR 8.2',
    'GR 8.3',
    'GR 8.4',
    'GR 8.5',
    'GR 8.6',
    'GR 9.1',
    'GR 9.2',
    'GR 9.3',
    'GR 9.4',
    'GR 9.5',
    'GR 9.6',
    'GR 10.1',
    'GR 10.2',
    'GR 10.3',
    'GR 10.4',
    'GR 10.5',
    'GR 10.6',
)

CREATORS: dict[str, Callable[[str], str]] = {
    '1.1': create_1_1_inertial_frames,
    '1.2': create_1_2_constancy_of_speed_of_light,
    '1.3': create_1_3_principle_of_relativity,
    '2.2': create_2_2_spacetime_event,
    '2.3': create_2_3_principle_of_locality,
    '3.1': create_3_1_metric_tensor,
    '3.2': create_3_2_spacetime_interval,
    '3.3': create_3_3_lorentz_transformations,
    '3.4': create_3_4_light_cone,
    '3.5': create_3_5_minkowski_diagram,
    '4.1': create_4_1_proper_time,
    '4.2': create_4_2_four_vectors,
    '4.3': create_4_3_position_four_vector,
    '4.4': create_4_4_velocity_four_vector,
    '4.5': create_4_5_momentum_four_vector,
    '4.6': create_4_6_mass_energy_equivalence,
    '5.1': create_5_1_lagrangian,
    '5.2': create_5_2_action_principle,
    '5.3': create_5_3_euler_lagrange,
    '5.4': create_5_4_canonical_momentum,
    '5.5': create_5_5_hamiltonian_formalism,
    '5.6': create_5_6_noethers_theorem,
    '6.1': create_6_1_scalar_field,
    '6.2': create_6_2_vector_field,
    '6.3': create_6_3_field_lagrangian,
    '6.4': create_6_4_field_equations,
    '7.1': create_7_1_vector_potential,
    '7.2': create_7_2_field_tensor,
    '7.3': create_7_3_electric_field,
    '7.4': create_7_4_magnetic_field,
    '7.5': create_7_5_electromagnetic_field,
    '7.6': create_7_6_four_current,
    '7.7': create_7_7_maxwells_equations,
    '8.1': create_8_1_gauge_invariance,
    '8.3': create_8_3_minimal_coupling,
    '8.4': create_8_4_lorentz_force_law,
    '8.5': create_8_5_charge_conservation,
    '8.6': create_8_6_lorenz_gauge,
    '9.1': create_9_1_energy_momentum_tensor,
    '9.2': create_9_2_poynting_vector,
    '9.3': create_9_3_em_stress_energy,
    '9.4': create_9_4_em_energy_density,
    '10.1': create_10_1_wave_equation,
    '10.2': create_10_2_electromagnetic_waves,
    '10.3': create_10_3_radiation_reaction,
    '11.1': create_11_1_lorentz_invariance,
    '11.2': create_11_2_gauge_fixing,
    'M 1.1': create_m_1_1_manifold,
    'M 1.2': create_m_1_2_coordinate_chart,
    'M 1.3': create_m_1_3_coordinate_transformation,
    'M 1.4': create_m_1_4_worldline,
    'M 1.5': create_m_1_5_tangent_space,
    'M 1.6': create_m_1_6_cotangent_space,
    'M 2.1': create_m_2_1_tensor_field,
    'M 2.2': create_m_2_2_index_notation,
    'M 2.3': create_m_2_3_tensor_transformation_law,
    'GR 1.1': create_gr_1_1_gravity_as_geometry,
    'GR 1.2': create_gr_1_2_equivalence_principle,
    'GR 1.3': create_gr_1_3_local_inertial_frame,
    'GR 1.4': create_gr_1_4_freely_falling_observer,
    'GR 1.5': create_gr_1_5_tidal_gravity,
    'GR 2.1': create_gr_2_1_spacetime_metric,
    'GR 2.2': create_gr_2_2_inverse_metric,
    'GR 2.3': create_gr_2_3_volume_element,
    'GR 3.1': create_gr_3_1_line_element,
    'GR 3.2': create_gr_3_2_proper_time,
    'GR 3.3': create_gr_3_3_null_curve,
    'GR 3.4': create_gr_3_4_causal_structure,
    'GR 3.5': create_gr_3_5_local_flatness,
    'GR 3.6': create_gr_3_6_metric_signature,
    'GR 4.1': create_gr_4_1_connection,
    'GR 4.2': create_gr_4_2_christoffel_symbols,
    'GR 4.3': create_gr_4_3_covariant_derivative,
    'GR 4.4': create_gr_4_4_metric_compatibility,
    'GR 4.5': create_gr_4_5_torsion_free,
    'GR 4.6': create_gr_4_6_parallel_transport,
    'GR 5.1': create_gr_5_1_geodesic,
    'GR 5.2': create_gr_5_2_geodesic_equation,
    'GR 5.3': create_gr_5_3_geodesic_action,
    'GR 5.4': create_gr_5_4_four_velocity,
    'GR 5.5': create_gr_5_5_four_acceleration,
    'GR 5.6': create_gr_5_6_geodesic_deviation,
    'GR 6.1': create_gr_6_1_riemann_tensor,
    'GR 6.2': create_gr_6_2_ricci_tensor,
    'GR 6.3': create_gr_6_3_ricci_scalar,
    'GR 6.4': create_gr_6_4_einstein_tensor,
    'GR 6.5': create_gr_6_5_bianchi_identity,
    'GR 6.6': create_gr_6_6_curvature_invariants,
    'GR 7.1': create_gr_7_1_stress_energy_tensor,
    'GR 7.2': create_gr_7_2_perfect_fluid,
    'GR 7.3': create_gr_7_3_energy_conditions,
    'GR 7.4': create_gr_7_4_covariant_conservation,
    'GR 7.5': create_gr_7_5_equation_of_state,
    'GR 8.1': create_gr_8_1_einstein_field_equations,
    'GR 8.2': create_gr_8_2_cosmological_constant,
    'GR 8.3': create_gr_8_3_einstein_hilbert_action,
    'GR 8.4': create_gr_8_4_stress_energy_variation,
    'GR 8.5': create_gr_8_5_trace_reversed_equations,
    'GR 8.6': create_gr_8_6_vacuum_field_equations,
    'GR 9.1': create_gr_9_1_weak_field_metric,
    'GR 9.2': create_gr_9_2_newtonian_limit,
    'GR 9.3': create_gr_9_3_gravitational_redshift,
    'GR 9.4': create_gr_9_4_light_deflection,
    'GR 9.5': create_gr_9_5_perihelion_precession,
    'GR 9.6': create_gr_9_6_post_newtonian_approximation,
    'GR 10.1': create_gr_10_1_schwarzschild_metric,
    'GR 10.2': create_gr_10_2_schwarzschild_radius,
    'GR 10.3': create_gr_10_3_event_horizon,
    'GR 10.4': create_gr_10_4_coordinate_singularity,
    'GR 10.5': create_gr_10_5_black_hole_singularity,
    'GR 10.6': create_gr_10_6_effective_potential_orbits,
}


def _svg_filename_id(node_id: str) -> str:
    """Return the file-safe id fragment used by saved SVG review files."""
    return node_id.replace(" ", "_").replace(".", "_")


def create_svg_graphic(node_id: str, variant: str = "icon") -> str | None:
    """Return an SVG XML string for a KG node id and variant, if known."""
    creator = CREATORS.get(str(node_id).strip())
    if creator is None:
        return None
    return creator(variant)


def save_svg_graphics(output_dir: str | Path = ".") -> None:
    """Write all currently implemented icon SVGs to files."""
    output = Path(output_dir)
    output.mkdir(parents=True, exist_ok=True)
    for node_id in IMPLEMENTED_NODE_IDS:
        svg = create_svg_graphic(node_id, variant="icon")
        if svg is not None:
            (output / f"image_{_svg_filename_id(node_id)}.svg").write_text(svg, encoding="utf-8")


__all__ = ["CREATORS", "IMPLEMENTED_NODE_IDS", "create_svg_graphic", "save_svg_graphics"]
