"""Registry and public dispatch helpers for concept SVG graphics."""

from __future__ import annotations

from pathlib import Path
from typing import Callable

from srkg.svg_graphics.concepts import (
    create_10_1_wave_equation,
    create_10_2_electromagnetic_waves,
    create_10_3_radiation_reaction,
    create_11_1_lorentz_invariance,
    create_11_2_gauge_fixing,
    create_1_1_inertial_frames,
    create_1_2_constancy_of_speed_of_light,
    create_1_3_principle_of_relativity,
    create_2_2_spacetime_event,
    create_2_3_principle_of_locality,
    create_3_1_metric_tensor,
    create_3_2_spacetime_interval,
    create_3_3_lorentz_transformations,
    create_3_4_light_cone,
    create_3_5_minkowski_diagram,
    create_4_1_proper_time,
    create_4_2_four_vectors,
    create_4_3_position_four_vector,
    create_4_4_velocity_four_vector,
    create_4_5_momentum_four_vector,
    create_4_6_mass_energy_equivalence,
    create_5_1_lagrangian,
    create_5_2_action_principle,
    create_5_3_euler_lagrange,
    create_5_4_canonical_momentum,
    create_5_5_hamiltonian_formalism,
    create_5_6_noethers_theorem,
    create_6_1_scalar_field,
    create_6_2_vector_field,
    create_6_3_field_lagrangian,
    create_6_4_field_equations,
    create_7_1_vector_potential,
    create_7_2_field_tensor,
    create_7_3_electric_field,
    create_7_4_magnetic_field,
    create_7_5_electromagnetic_field,
    create_7_6_four_current,
    create_7_7_maxwells_equations,
    create_8_1_gauge_invariance,
    create_8_3_minimal_coupling,
    create_8_4_lorentz_force_law,
    create_8_5_charge_conservation,
    create_8_6_lorenz_gauge,
    create_9_1_energy_momentum_tensor,
    create_9_2_poynting_vector,
    create_9_3_em_stress_energy,
    create_9_4_em_energy_density,
    create_gr_1_1_gravity_as_geometry,
    create_gr_1_2_equivalence_principle,
    create_gr_1_3_local_inertial_frame,
    create_gr_1_4_freely_falling_observer,
    create_gr_1_5_tidal_gravity,
    create_gr_7_1_stress_energy_tensor,
    create_gr_7_2_perfect_fluid,
    create_gr_7_3_energy_conditions,
    create_gr_7_4_covariant_conservation,
    create_gr_7_5_equation_of_state,
    create_gr_8_1_einstein_field_equations,
    create_gr_8_2_cosmological_constant,
    create_gr_8_3_einstein_hilbert_action,
    create_gr_8_4_stress_energy_variation,
    create_gr_8_5_trace_reversed_equations,
    create_gr_8_6_vacuum_field_equations,
    create_gr_9_1_weak_field_metric,
    create_gr_9_2_newtonian_limit,
    create_gr_9_3_gravitational_redshift,
    create_gr_9_4_light_deflection,
    create_gr_9_5_perihelion_precession,
    create_gr_9_6_post_newtonian_approximation,
    create_gr_10_1_schwarzschild_metric,
    create_gr_10_2_schwarzschild_radius,
    create_gr_10_3_event_horizon,
    create_gr_10_4_coordinate_singularity,
    create_gr_10_5_black_hole_singularity,
    create_gr_10_6_effective_potential_orbits,
    create_m_1_1_manifold,
    create_m_1_2_coordinate_chart,
    create_m_1_3_coordinate_transformation,
    create_m_1_4_worldline,
    create_m_1_5_tangent_space,
    create_m_1_6_cotangent_space,
    create_m_2_1_tensor_field,
    create_m_2_2_index_notation,
    create_m_2_3_tensor_transformation_law,
    create_gr_2_1_spacetime_metric,
    create_gr_2_2_inverse_metric,
    create_gr_2_3_volume_element,
    create_gr_3_1_line_element, create_gr_3_2_proper_time,
    create_gr_3_3_null_curve, create_gr_3_4_causal_structure,
    create_gr_3_5_local_flatness, create_gr_3_6_metric_signature,
    create_gr_4_1_connection, create_gr_4_2_christoffel_symbols,
    create_gr_4_3_covariant_derivative, create_gr_4_4_metric_compatibility,
    create_gr_4_5_torsion_free, create_gr_4_6_parallel_transport,
    create_gr_5_1_geodesic, create_gr_5_2_geodesic_equation,
    create_gr_5_3_geodesic_action, create_gr_5_4_four_velocity,
    create_gr_5_5_four_acceleration, create_gr_5_6_geodesic_deviation,
    create_gr_6_1_riemann_tensor, create_gr_6_2_ricci_tensor,
    create_gr_6_3_ricci_scalar, create_gr_6_4_einstein_tensor,
    create_gr_6_5_bianchi_identity, create_gr_6_6_curvature_invariants,
)

IMPLEMENTED_NODE_IDS = (
    'sr.inertial_frames',
    'sr.constancy_of_speed_of_light',
    'sr.principle_of_relativity',
    'sr.spacetime_event',
    'sr.principle_of_locality',
    'sr.metric_tensor',
    'sr.spacetime_interval',
    'sr.lorentz_transformations',
    'sr.light_cone',
    'sr.minkowski_diagram',
    'sr.proper_time',
    'sr.four_vectors',
    'sr.position_four_vector',
    'sr.velocity_four_vector',
    'sr.momentum_four_vector',
    'sr.mass_energy_equivalence',
    'sr.lagrangian',
    'sr.action_principle',
    'sr.euler_lagrange_equations',
    'sr.canonical_momentum',
    'sr.hamiltonian_formalism',
    'sr.noether_theorem',
    'sr.scalar_field',
    'sr.vector_field',
    'sr.field_lagrangian',
    'sr.field_equations',
    'sr.vector_potential',
    'sr.field_tensor',
    'sr.electric_field',
    'sr.magnetic_field',
    'sr.electromagnetic_field',
    'sr.four_current',
    'sr.maxwells_equations',
    'sr.gauge_invariance',
    'sr.minimal_coupling',
    'sr.lorentz_force_law',
    'sr.charge_conservation',
    'sr.lorenz_gauge',
    'sr.energy_momentum_tensor',
    'sr.poynting_vector',
    'sr.em_stress_energy',
    'sr.em_energy_density',
    'sr.wave_equation',
    'sr.electromagnetic_waves',
    'sr.radiation_reaction',
    'sr.lorentz_invariance',
    'sr.gauge_fixing',
    'math.manifold',
    'math.coordinate_chart',
    'math.coordinate_transformation',
    'math.worldline',
    'math.tangent_space',
    'math.cotangent_space',
    'math.tensor_field',
    'math.index_notation',
    'math.tensor_transformation_law',
    'gr.gravity_as_geometry',
    'gr.equivalence_principle',
    'gr.local_inertial_frame',
    'gr.freely_falling_observer',
    'gr.tidal_gravity',
    'gr.metric_tensor',
    'gr.inverse_metric',
    'gr.volume_element',
    'gr.line_element', 'gr.proper_time', 'gr.null_curve', 'gr.causal_structure', 'gr.local_flatness', 'gr.metric_signature',
    'gr.connection', 'gr.christoffel_symbols', 'gr.covariant_derivative', 'gr.metric_compatibility', 'gr.torsion_free_connection', 'gr.parallel_transport',
    'gr.geodesic', 'gr.geodesic_equation', 'gr.geodesic_action', 'gr.four_velocity', 'gr.four_acceleration', 'gr.geodesic_deviation',
    'gr.riemann_tensor', 'gr.ricci_tensor', 'gr.ricci_scalar', 'gr.einstein_tensor', 'gr.bianchi_identity', 'gr.curvature_invariants',
    'gr.stress_energy_tensor',
    'gr.perfect_fluid',
    'gr.energy_conditions',
    'gr.covariant_conservation',
    'gr.equation_of_state',
    'gr.einstein_field_equations',
    'gr.cosmological_constant',
    'gr.einstein_hilbert_action',
    'gr.stress_energy_variation',
    'gr.trace_reversed_equations',
    'gr.vacuum_field_equations',
    'gr.weak_field_metric',
    'gr.newtonian_limit',
    'gr.gravitational_redshift',
    'gr.light_deflection',
    'gr.perihelion_precession',
    'gr.post_newtonian_approximation',
    'gr.schwarzschild_metric',
    'gr.schwarzschild_radius',
    'gr.event_horizon',
    'gr.coordinate_singularity',
    'gr.black_hole_singularity',
    'gr.effective_potential_orbits',
)

CREATORS: dict[str, Callable[[str], str]] = {
    'sr.inertial_frames': create_1_1_inertial_frames,
    'sr.constancy_of_speed_of_light': create_1_2_constancy_of_speed_of_light,
    'sr.principle_of_relativity': create_1_3_principle_of_relativity,
    'sr.spacetime_event': create_2_2_spacetime_event,
    'sr.principle_of_locality': create_2_3_principle_of_locality,
    'sr.metric_tensor': create_3_1_metric_tensor,
    'sr.spacetime_interval': create_3_2_spacetime_interval,
    'sr.lorentz_transformations': create_3_3_lorentz_transformations,
    'sr.light_cone': create_3_4_light_cone,
    'sr.minkowski_diagram': create_3_5_minkowski_diagram,
    'sr.proper_time': create_4_1_proper_time,
    'sr.four_vectors': create_4_2_four_vectors,
    'sr.position_four_vector': create_4_3_position_four_vector,
    'sr.velocity_four_vector': create_4_4_velocity_four_vector,
    'sr.momentum_four_vector': create_4_5_momentum_four_vector,
    'sr.mass_energy_equivalence': create_4_6_mass_energy_equivalence,
    'sr.lagrangian': create_5_1_lagrangian,
    'sr.action_principle': create_5_2_action_principle,
    'sr.euler_lagrange_equations': create_5_3_euler_lagrange,
    'sr.canonical_momentum': create_5_4_canonical_momentum,
    'sr.hamiltonian_formalism': create_5_5_hamiltonian_formalism,
    'sr.noether_theorem': create_5_6_noethers_theorem,
    'sr.scalar_field': create_6_1_scalar_field,
    'sr.vector_field': create_6_2_vector_field,
    'sr.field_lagrangian': create_6_3_field_lagrangian,
    'sr.field_equations': create_6_4_field_equations,
    'sr.vector_potential': create_7_1_vector_potential,
    'sr.field_tensor': create_7_2_field_tensor,
    'sr.electric_field': create_7_3_electric_field,
    'sr.magnetic_field': create_7_4_magnetic_field,
    'sr.electromagnetic_field': create_7_5_electromagnetic_field,
    'sr.four_current': create_7_6_four_current,
    'sr.maxwells_equations': create_7_7_maxwells_equations,
    'sr.gauge_invariance': create_8_1_gauge_invariance,
    'sr.minimal_coupling': create_8_3_minimal_coupling,
    'sr.lorentz_force_law': create_8_4_lorentz_force_law,
    'sr.charge_conservation': create_8_5_charge_conservation,
    'sr.lorenz_gauge': create_8_6_lorenz_gauge,
    'sr.energy_momentum_tensor': create_9_1_energy_momentum_tensor,
    'sr.poynting_vector': create_9_2_poynting_vector,
    'sr.em_stress_energy': create_9_3_em_stress_energy,
    'sr.em_energy_density': create_9_4_em_energy_density,
    'sr.wave_equation': create_10_1_wave_equation,
    'sr.electromagnetic_waves': create_10_2_electromagnetic_waves,
    'sr.radiation_reaction': create_10_3_radiation_reaction,
    'sr.lorentz_invariance': create_11_1_lorentz_invariance,
    'sr.gauge_fixing': create_11_2_gauge_fixing,
    'math.manifold': create_m_1_1_manifold,
    'math.coordinate_chart': create_m_1_2_coordinate_chart,
    'math.coordinate_transformation': create_m_1_3_coordinate_transformation,
    'math.worldline': create_m_1_4_worldline,
    'math.tangent_space': create_m_1_5_tangent_space,
    'math.cotangent_space': create_m_1_6_cotangent_space,
    'math.tensor_field': create_m_2_1_tensor_field,
    'math.index_notation': create_m_2_2_index_notation,
    'math.tensor_transformation_law': create_m_2_3_tensor_transformation_law,
    'gr.gravity_as_geometry': create_gr_1_1_gravity_as_geometry,
    'gr.equivalence_principle': create_gr_1_2_equivalence_principle,
    'gr.local_inertial_frame': create_gr_1_3_local_inertial_frame,
    'gr.freely_falling_observer': create_gr_1_4_freely_falling_observer,
    'gr.tidal_gravity': create_gr_1_5_tidal_gravity,
    'gr.metric_tensor': create_gr_2_1_spacetime_metric,
    'gr.inverse_metric': create_gr_2_2_inverse_metric,
    'gr.volume_element': create_gr_2_3_volume_element,
    'gr.line_element': create_gr_3_1_line_element,
    'gr.proper_time': create_gr_3_2_proper_time,
    'gr.null_curve': create_gr_3_3_null_curve,
    'gr.causal_structure': create_gr_3_4_causal_structure,
    'gr.local_flatness': create_gr_3_5_local_flatness,
    'gr.metric_signature': create_gr_3_6_metric_signature,
    'gr.connection': create_gr_4_1_connection,
    'gr.christoffel_symbols': create_gr_4_2_christoffel_symbols,
    'gr.covariant_derivative': create_gr_4_3_covariant_derivative,
    'gr.metric_compatibility': create_gr_4_4_metric_compatibility,
    'gr.torsion_free_connection': create_gr_4_5_torsion_free,
    'gr.parallel_transport': create_gr_4_6_parallel_transport,
    'gr.geodesic': create_gr_5_1_geodesic,
    'gr.geodesic_equation': create_gr_5_2_geodesic_equation,
    'gr.geodesic_action': create_gr_5_3_geodesic_action,
    'gr.four_velocity': create_gr_5_4_four_velocity,
    'gr.four_acceleration': create_gr_5_5_four_acceleration,
    'gr.geodesic_deviation': create_gr_5_6_geodesic_deviation,
    'gr.riemann_tensor': create_gr_6_1_riemann_tensor,
    'gr.ricci_tensor': create_gr_6_2_ricci_tensor,
    'gr.ricci_scalar': create_gr_6_3_ricci_scalar,
    'gr.einstein_tensor': create_gr_6_4_einstein_tensor,
    'gr.bianchi_identity': create_gr_6_5_bianchi_identity,
    'gr.curvature_invariants': create_gr_6_6_curvature_invariants,
    'gr.stress_energy_tensor': create_gr_7_1_stress_energy_tensor,
    'gr.perfect_fluid': create_gr_7_2_perfect_fluid,
    'gr.energy_conditions': create_gr_7_3_energy_conditions,
    'gr.covariant_conservation': create_gr_7_4_covariant_conservation,
    'gr.equation_of_state': create_gr_7_5_equation_of_state,
    'gr.einstein_field_equations': create_gr_8_1_einstein_field_equations,
    'gr.cosmological_constant': create_gr_8_2_cosmological_constant,
    'gr.einstein_hilbert_action': create_gr_8_3_einstein_hilbert_action,
    'gr.stress_energy_variation': create_gr_8_4_stress_energy_variation,
    'gr.trace_reversed_equations': create_gr_8_5_trace_reversed_equations,
    'gr.vacuum_field_equations': create_gr_8_6_vacuum_field_equations,
    'gr.weak_field_metric': create_gr_9_1_weak_field_metric,
    'gr.newtonian_limit': create_gr_9_2_newtonian_limit,
    'gr.gravitational_redshift': create_gr_9_3_gravitational_redshift,
    'gr.light_deflection': create_gr_9_4_light_deflection,
    'gr.perihelion_precession': create_gr_9_5_perihelion_precession,
    'gr.post_newtonian_approximation': create_gr_9_6_post_newtonian_approximation,
    'gr.schwarzschild_metric': create_gr_10_1_schwarzschild_metric,
    'gr.schwarzschild_radius': create_gr_10_2_schwarzschild_radius,
    'gr.event_horizon': create_gr_10_3_event_horizon,
    'gr.coordinate_singularity': create_gr_10_4_coordinate_singularity,
    'gr.black_hole_singularity': create_gr_10_5_black_hole_singularity,
    'gr.effective_potential_orbits': create_gr_10_6_effective_potential_orbits,
}


def _svg_filename_id(node_id: str) -> str:
    """Return the file-safe id fragment used by saved SVG review files."""
    return node_id.replace(" ", "_").replace(".", "_")


def create_svg_graphic(node_id: str, variant: str = "icon") -> str | None:
    """Return an SVG XML string for a KG node id and variant, if known."""
    creator = CREATORS.get(str(node_id).strip())
    if creator is None:
        return None
    return creator(variant)


def save_svg_graphics(output_dir: str | Path = ".") -> None:
    """Write all currently implemented icon SVGs to files."""
    output = Path(output_dir)
    output.mkdir(parents=True, exist_ok=True)
    for node_id in IMPLEMENTED_NODE_IDS:
        svg = create_svg_graphic(node_id, variant="icon")
        if svg is not None:
            (output / f"image_{_svg_filename_id(node_id)}.svg").write_text(svg, encoding="utf-8")


__all__ = ["CREATORS", "IMPLEMENTED_NODE_IDS", "create_svg_graphic", "save_svg_graphics"]
